version: "3"

services:
  app:
    image: docker.pkg.github.com/yarmsl/backend-ural_polymer/backend-uralpolymer:develop
    volumes:
      - pldr_volume:/app/uploads
    container_name: polydor-server-container
    build:
      context: ../backend-ural_polymer
    restart: always
    ports:
      - 5000:5000
    networks: 
      - pldr_network
  web:
    image: docker.pkg.github.com/yarmsl/frontend-ural_polymer/frontend-uralpolymer
    container_name: polydor-front-container
    build:
      context: .
  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./build:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks: 
      - pldr_network
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
volumes:
  pldr_volume:
networks:
  pldr_network:
    driver: bridge