version: "3"

services:
  app:
    image: docker.pkg.github.com/yarmsl/express-server/console-logbook-server:develop
    volumes:
      - cslb_volume:/app/uploads
    container_name: console-logbook-server-container
    build:
      context: ../express-server
    restart: always
    ports:
      - 5000:5000
    networks: 
      - cslb_network
  web:
    image: docker.pkg.github.com/yarmsl/console.logbook/console-logbook-front
    container_name: console-logbook-front-container
    build:
      context: .
    ports:
      - 80:80
      - 443:443
    networks: 
      - cslb_network
volumes:
  cslb_volume:
networks:
  cslb_network:
    driver: bridge