version: "3"

services:
  app:
    image: docker.pkg.github.com/yarmsl/backend-ural_polymer/backend-uralpolymer:develop
    volumes:
      - pldr_volume:/app/uploads
    container_name: polydor-server-container
    build:
      context: ../backend-ural_polymer
    restart: always
    ports:
      - 5000:5000
    networks: 
      - pldr_network
  web:
    image: docker.pkg.github.com/yarmsl/frontend-ural_polymer/frontend-uralpolymer
    container_name: polydor-front-container
    build:
      context: .
    ports:
      - 80:80
    networks: 
      - pldr_network
volumes:
  pldr_volume:
networks:
  pldr_network:
    driver: bridge