name: Deploy ConsoleLogbook Front

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@master
        - name: Publish to Registry
          uses: elgohr/Publish-Docker-Github-Action@master
          with:
            registry: docker.pkg.github.com
            name: docker.pkg.github.com/yarmsl/console.logbook/console-logbook-front
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            tags: "develop"